version: '3.8'

services:
  gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - postgres

  user-microservice:
    build: ./user_microservice
    ports:
      - "8082:8082"
      - "50052:50052"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - postgres

  auth-microservice:
    build: ./auth_microservice
    ports:
      - "8081:8081"
      - "50051:50051"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - postgres

  blog-microservice:
    build: ./blog_service
    ports:
      - "8083:8083"
      - "50053:50053"
    environment:     
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - postgres

  blog_recommender:
    build: ./blog_recommender
    ports:
      - "8085:8085"
    depends_on:
      - postgres
      - neo4j

  # tour-microservice:
  #   build: ./tour_service
  #   ports:
  #     - "8084:8084"
  #     - "50054:50054"
  #   environment:     
  #     - DB_HOST=postgres
  #     - DB_USER=postgres
  #     - DB_PASSWORD=postgres
  #     - DB_NAME=postgres
  #   depends_on:
  #     - postgres
  
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d/
      - postgres_data:/var/lib/postgresql/data
      
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/123456789
    volumes:
      - neo4j_data:/data

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongodb_data:/data
  
  nais-gateway:
    build: ./nais-gateway
    ports:
      - "8088:8088"
    environment:     
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - PYTHONUNBUFFERED=1
    depends_on:
      - postgres
      - blog_recommender
      - blog-microservice
      - auth-microservice
      - user-microservice
      - neo4j


volumes:
  postgres_data:
  neo4j_data:
  # mongodb_data:
