# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Install libpq-dev package
RUN apt-get update && apt-get install -y libpq-dev

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Run the migration script when the container launches
CMD ["python", "migration_script.py"]
