// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.0
// source: tour.proto

package invoicer

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TourServiceClient is the client API for TourService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TourServiceClient interface {
	GetAllToursGuide(ctx context.Context, in *GetAllToursGuideRequest, opts ...grpc.CallOption) (*TourList, error)
	CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*Tour, error)
	AddCheckpoint(ctx context.Context, in *AddCheckpointRequest, opts ...grpc.CallOption) (*AddCheckpointResponse, error)
	GetAllToursTourist(ctx context.Context, in *GetAllToursTouristRequest, opts ...grpc.CallOption) (*TourList, error)
	DeleteTour(ctx context.Context, in *DeleteTourRequest, opts ...grpc.CallOption) (*DeleteTourResponse, error)
}

type tourServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTourServiceClient(cc grpc.ClientConnInterface) TourServiceClient {
	return &tourServiceClient{cc}
}

func (c *tourServiceClient) GetAllToursGuide(ctx context.Context, in *GetAllToursGuideRequest, opts ...grpc.CallOption) (*TourList, error) {
	out := new(TourList)
	err := c.cc.Invoke(ctx, "/tour_service.TourService/GetAllToursGuide", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) CreateTour(ctx context.Context, in *CreateTourRequest, opts ...grpc.CallOption) (*Tour, error) {
	out := new(Tour)
	err := c.cc.Invoke(ctx, "/tour_service.TourService/CreateTour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) AddCheckpoint(ctx context.Context, in *AddCheckpointRequest, opts ...grpc.CallOption) (*AddCheckpointResponse, error) {
	out := new(AddCheckpointResponse)
	err := c.cc.Invoke(ctx, "/tour_service.TourService/AddCheckpoint", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) GetAllToursTourist(ctx context.Context, in *GetAllToursTouristRequest, opts ...grpc.CallOption) (*TourList, error) {
	out := new(TourList)
	err := c.cc.Invoke(ctx, "/tour_service.TourService/GetAllToursTourist", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tourServiceClient) DeleteTour(ctx context.Context, in *DeleteTourRequest, opts ...grpc.CallOption) (*DeleteTourResponse, error) {
	out := new(DeleteTourResponse)
	err := c.cc.Invoke(ctx, "/tour_service.TourService/DeleteTour", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TourServiceServer is the server API for TourService service.
// All implementations must embed UnimplementedTourServiceServer
// for forward compatibility
type TourServiceServer interface {
	GetAllToursGuide(context.Context, *GetAllToursGuideRequest) (*TourList, error)
	CreateTour(context.Context, *CreateTourRequest) (*Tour, error)
	AddCheckpoint(context.Context, *AddCheckpointRequest) (*AddCheckpointResponse, error)
	GetAllToursTourist(context.Context, *GetAllToursTouristRequest) (*TourList, error)
	DeleteTour(context.Context, *DeleteTourRequest) (*DeleteTourResponse, error)
	mustEmbedUnimplementedTourServiceServer()
}

// UnimplementedTourServiceServer must be embedded to have forward compatible implementations.
type UnimplementedTourServiceServer struct {
}

func (UnimplementedTourServiceServer) GetAllToursGuide(context.Context, *GetAllToursGuideRequest) (*TourList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllToursGuide not implemented")
}
func (UnimplementedTourServiceServer) CreateTour(context.Context, *CreateTourRequest) (*Tour, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTour not implemented")
}
func (UnimplementedTourServiceServer) AddCheckpoint(context.Context, *AddCheckpointRequest) (*AddCheckpointResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddCheckpoint not implemented")
}
func (UnimplementedTourServiceServer) GetAllToursTourist(context.Context, *GetAllToursTouristRequest) (*TourList, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllToursTourist not implemented")
}
func (UnimplementedTourServiceServer) DeleteTour(context.Context, *DeleteTourRequest) (*DeleteTourResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTour not implemented")
}
func (UnimplementedTourServiceServer) mustEmbedUnimplementedTourServiceServer() {}

// UnsafeTourServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TourServiceServer will
// result in compilation errors.
type UnsafeTourServiceServer interface {
	mustEmbedUnimplementedTourServiceServer()
}

func RegisterTourServiceServer(s grpc.ServiceRegistrar, srv TourServiceServer) {
	s.RegisterService(&TourService_ServiceDesc, srv)
}

func _TourService_GetAllToursGuide_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllToursGuideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetAllToursGuide(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour_service.TourService/GetAllToursGuide",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetAllToursGuide(ctx, req.(*GetAllToursGuideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_CreateTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).CreateTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour_service.TourService/CreateTour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).CreateTour(ctx, req.(*CreateTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_AddCheckpoint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddCheckpointRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).AddCheckpoint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour_service.TourService/AddCheckpoint",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).AddCheckpoint(ctx, req.(*AddCheckpointRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_GetAllToursTourist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllToursTouristRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).GetAllToursTourist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour_service.TourService/GetAllToursTourist",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).GetAllToursTourist(ctx, req.(*GetAllToursTouristRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TourService_DeleteTour_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTourRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TourServiceServer).DeleteTour(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tour_service.TourService/DeleteTour",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TourServiceServer).DeleteTour(ctx, req.(*DeleteTourRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TourService_ServiceDesc is the grpc.ServiceDesc for TourService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TourService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tour_service.TourService",
	HandlerType: (*TourServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllToursGuide",
			Handler:    _TourService_GetAllToursGuide_Handler,
		},
		{
			MethodName: "CreateTour",
			Handler:    _TourService_CreateTour_Handler,
		},
		{
			MethodName: "AddCheckpoint",
			Handler:    _TourService_AddCheckpoint_Handler,
		},
		{
			MethodName: "GetAllToursTourist",
			Handler:    _TourService_GetAllToursTourist_Handler,
		},
		{
			MethodName: "DeleteTour",
			Handler:    _TourService_DeleteTour_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tour.proto",
}
