# Koristimo zvaničnu Go sliku kao osnovu
FROM golang:latest

# Postavljamo radni direktorijum unutar kontejnera
WORKDIR /app

# Kopiramo go.mod i go.sum fajlove
COPY go.mod go.sum ./

# Preuzimamo zavisnosti
RUN go mod download

# Kopiramo izvorni kod u kontejner
COPY . .

# Kompajliramo Go aplikaciju
RUN go build -o /auth-microservice

# Otvaramo port na kojem će mikroservis slušati
EXPOSE 8081
EXPOSE 50051

# Pokrećemo mikroservis
CMD [ "/auth-microservice" ]
